name: Saludo usando variables y secretos
on:
  workflow_dispatch
env:
  DIA_DE_SEMANA: Lunes
jobs:
  saludo_variables:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludo variables
        run: echo "$SALUDO, ${{ VARS.nombre}}. Hoy es {{ env.DIA_DE_SEMANA }}!"
  saludos-secretos:
    runs-on: ubuntu-latest
    steps:
      - name: Saludo secretos
        run: echo "$SALUDO, ${{vars.NOMBRE}}. Tu contraseña es ${{ secrets.CONTRASENA }}"
    
